grails-app/domain/grupodot/Prestamista.groovy
package grupodot

class Prestamista {

    String nombre
    float tasa
    int montoMaximo

    static constraints = {
    }

    static  hasMany = [
            prestamo:Prestamo
    ]

    static mapping = {
        version false
    }
}

grails-app/domain/grupodot/Prestamo.groovy
package grupodot

class Prestamo {

    int montoPrestamo
    int cuotaMensual
    int pagoTotalCredito
    float tasaInteresMensual

    static constraints = {
    }

    static belongsTo = [
            prestamista:Prestamista
    ]

    static mapping = {
        version false
    }
}

grails-app/controllers/grupodot/PrestamistaController.groovy
package grupodot

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class PrestamistaController {

    PrestamistaService prestamistaService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond prestamistaService.list(params), model:[prestamistaCount: prestamistaService.count()]
    }

    def show(Long id) {
        respond prestamistaService.get(id)
    }

    def create() {
        respond new Prestamista(params)
    }

    def save(Prestamista prestamista) {
        if (prestamista == null) {
            notFound()
            return
        }

        try {
            prestamistaService.save(prestamista)
        } catch (ValidationException e) {
            respond prestamista.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'prestamista.label', default: 'Prestamista'), prestamista.id])
                redirect prestamista
            }
            '*' { respond prestamista, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond prestamistaService.get(id)
    }

    def update(Prestamista prestamista) {
        if (prestamista == null) {
            notFound()
            return
        }

        try {
            prestamistaService.save(prestamista)
        } catch (ValidationException e) {
            respond prestamista.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'prestamista.label', default: 'Prestamista'), prestamista.id])
                redirect prestamista
            }
            '*'{ respond prestamista, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        prestamistaService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'prestamista.label', default: 'Prestamista'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'prestamista.label', default: 'Prestamista'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/grupodot/PrestamoController.groovy
package grupodot

import grails.validation.ValidationException

import java.text.DecimalFormat

import static org.springframework.http.HttpStatus.*

class PrestamoController {

    PrestamoService prestamoService

    static allowedMethods = [save: "POST", show: "GET"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond prestamoService.list(params), model:[prestamoCount: prestamoService.count()]
    }

    def show(Long id) {
        respond prestamoService.get(id)
    }

    def create() {
        respond new Prestamo(params)
    }

    def save(Prestamo prestamo) {
        if (prestamo == null) {
            notFound()
            return
        }

        try {
            prestamoService.save(prestamo)
        } catch (ValidationException e) {
            respond prestamo.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'prestamo.label', default: 'Prestamo'), prestamo.id])
                redirect prestamo
            }
            '*' { respond prestamo, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond prestamoService.get(id)
    }

    def update(Prestamo prestamo) {
        if (prestamo == null) {
            notFound()
            return
        }

        try {
            prestamoService.save(prestamo)
        } catch (ValidationException e) {
            respond prestamo.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'prestamo.label', default: 'Prestamo'), prestamo.id])
                redirect prestamo
            }
            '*'{ respond prestamo, [status: OK] }
        }
    }


    def calcularCotizacion(){


        String msj=""
        def usuarioPrestamista
        double cuotaMensual
        double valorAPagar
        DecimalFormat df2 = new DecimalFormat("##.00");

        try {
            if(params.montoPrestamo && request.method=='POST'){
                int montoPrestamo=Integer.parseInt(params.montoPrestamo)
                def usuarioPrestamistaQuery="From Prestamista p where p.montoMaximo>${montoPrestamo} Order By p.tasa"
                usuarioPrestamista=Prestamista.executeQuery(usuarioPrestamistaQuery)[0]

                if(usuarioPrestamista)
                {
                    double tasaUsuarioPrestamista=usuarioPrestamista.tasa/100
                    int plazoFijo=36
                    valorAPagar=montoPrestamo*(1+plazoFijo*tasaUsuarioPrestamista)
                    cuotaMensual=valorAPagar/plazoFijo

                    //println request.JSON["name"]
                }
                else
                    msj="No hay gente que cumpla  con los requisitos"
            }
            else
            {
                if(request.method!='POST')
                {
                    response.status=500
                    msj="Método no autorizado"
                }
                else
                    msj="No se ha ingresado información"

            }

        }catch(Exception ex){
            msj="Verifique la información!"
        }



        render view: "solicitarPrestamo",model: [valorAPagar:df2.format(valorAPagar)?:'',usuarioPrestamista:usuarioPrestamista,
                                                 cuotaMensual:df2.format(cuotaMensual)?:'',msj:msj]

    }






    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        prestamoService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'prestamo.label', default: 'Prestamo'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'prestamo.label', default: 'Prestamo'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/grupodot/UrlMappings.groovy
package grupodot

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')


    }
}

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>
<body>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#">
		    <asset:image src="grails.svg" alt="Grails Logo"/>
                </a>
            </div>
            <div class="navbar-collapse collapse" aria-expanded="false" style="height: 0.8px;">
                <ul class="nav navbar-nav navbar-right">
                    <g:pageProperty name="page.nav" />
                </ul>
            </div>
        </div>
    </div>

    <g:layoutBody/>

    <div class="footer" role="contentinfo"></div>

    <div id="spinner" class="spinner" style="display:none;">
        <g:message code="spinner.alt" default="Loading&hellip;"/>
    </div>

    <asset:javascript src="application.js"/>

</body>
</html>

grails-app/views/prestamista/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'prestamista.label', default: 'Prestamista')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-prestamista" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-prestamista" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.prestamista}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.prestamista}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.prestamista}" method="POST">
                <fieldset class="form">
                    <f:all bean="prestamista"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/prestamista/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'prestamista.label', default: 'Prestamista')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-prestamista" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-prestamista" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.prestamista}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.prestamista}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.prestamista}" method="PUT">
                <g:hiddenField name="version" value="${this.prestamista?.version}" />
                <fieldset class="form">
                    <f:all bean="prestamista"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/prestamista/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'prestamista.label', default: 'Prestamista')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-prestamista" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-prestamista" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${prestamistaList}" properties="['nombre','tasa','montoMaximo']" />

            <div class="pagination">
                <g:paginate total="${prestamistaCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/prestamista/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'prestamista.label', default: 'Prestamista')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-prestamista" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-prestamista" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="prestamista" />
            <g:form resource="${this.prestamista}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.prestamista}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/prestamo/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'prestamo.label', default: 'Prestamo')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-prestamo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-prestamo" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.prestamo}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.prestamo}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.prestamo}" method="POST">
                <fieldset class="form">
                    <f:all bean="prestamo"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/prestamo/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'prestamo.label', default: 'Prestamo')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-prestamo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-prestamo" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.prestamo}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.prestamo}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.prestamo}" method="PUT">
                <g:hiddenField name="version" value="${this.prestamo?.version}" />
                <fieldset class="form">
                    <f:all bean="prestamo"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/prestamo/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'prestamo.label', default: 'Prestamo')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-prestamo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-prestamo" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${prestamoList}" />

            <div class="pagination">
                <g:paginate total="${prestamoCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/prestamo/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'prestamo.label', default: 'Prestamo')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-prestamo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-prestamo" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="prestamo" />
            <g:form resource="${this.prestamo}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.prestamo}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/prestamo/solicitarPrestamo.gsp
<%--
  Created by IntelliJ IDEA.
  User: 1045721591
  Date: 7/09/2018
  Time: 11:04 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title>Solicitar Prestamo</title>
</head>

<body>
    <g:form name="solicitoPrestamo" controller="prestamo" action="calcularCotizacion">
        <g:message default="Monto préstamo" message="Monto préstamo"/>
        <g:textField name="montoPrestamo" value="${params.montoPrestamo}" />
        <g:submitButton name="Calcular cotización" />
    </g:form>

    <g:message default="Monto préstamo" message="Valor a Pagar"/>
    <g:textField name="ajaxCall" value="${valorAPagar}" disabled="true"/>
    <br><br>
    <table border="2">
        <tr>
            <td><b>Socio que realiza el préstamo</b></td>
            <td><b>Cuota Mensual</b></td>
            <td><b>Pago total del crédito</b></td>
            <td><b>Tasa de interés mensual</b></td>
        </tr>
        <tr>
            <td>${usuarioPrestamista?.nombre?:''}</td>
            <td>$ ${cuotaMensual}</td>
            <td>$ ${valorAPagar}</td>
            <td>${usuarioPrestamista?.tasa?:''}%</td>
        </tr>

    </table>

<g:if test="${!usuarioPrestamista}">
    <h1>${msj}</h1>
</g:if>




</body>
</html>